name: test
on:
    workflow_dispatch:
        inputs:
            key:
                description: 'Key'
                required: true
                default: 'default'
    push:
        branches:
            - main

concurrency:
  group: build-${{ github.run_id }}  # Unique concurrency group per workflow run
  cancel-in-progress: true  # Ensure queued workflows are not canceled

jobs:
  build:
    name: Sample step
    runs-on: ubuntu-latest
    steps:
      - name: Sample step
        run: |
          echo "Sample step"
          echo "${{ github.event.inputs.key }}"
          sleep 20s
          exit 1
